import { gameboardFactory } from "./gameboard.mjs";

test('placeShip function adds ship', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([1, 3], 3, 'vertical')
  expect(gameboardObject.getAllShips()[0]).toHaveProperty('ship')
})
test('placeShip function adds ship index', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([1, 3], 3, 'vertical')
  expect(gameboardObject.getAllShips()[0]).toHaveProperty('index', [1, 3])
})
test('placeShip function adds ship direction', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([1, 3], 3, 'vertical')
  expect(gameboardObject.getAllShips()[0]).toHaveProperty('direction', 'vertical')
})
test('receiveAttack function logs attack coords', () => {
  const gameboardObject = gameboardFactory()
  expect(gameboardObject.receiveAttack([1, 3])[0][0]).toEqual([1, 3])
})
test('receiveAttack function notes if there is a miss', () => {
  const gameboardObject = gameboardFactory()
  expect(gameboardObject.receiveAttack([1, 3])).toEqual([ [ [1, 3], false ] ])
})
test('receiveAttack logs repeated attack coords', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.receiveAttack([4, 7])
  expect(gameboardObject.receiveAttack([1, 3])).toEqual([ [ [4, 7], false ], [ [1, 3], false ] ])
})
test('receiveAttack function notes if there is a hit', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([1, 2], 3, 'vertical')
  expect(gameboardObject.receiveAttack([1, 3])).toEqual([ [ [1, 3], true ] ])
})
test('retrieve array of attacks received', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([1, 2], 3, 'vertical')
  gameboardObject.receiveAttack([1, 3])
  expect(gameboardObject.getAttacksReceived()).toEqual([ [ [1, 3], true ] ])
})
test('check that all ships have not been sunk', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([2, 4], 3, 'horizontal')
  expect(gameboardObject.areShipsSunk()).toBe(false)
})
test('check that all ships have been sunk, with one ship', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([2, 4], 3, 'horizontal')
  gameboardObject.receiveAttack([2, 4])
  gameboardObject.receiveAttack([3, 4])
  gameboardObject.receiveAttack([4, 4])
  expect(gameboardObject.areShipsSunk()).toBe(true)
})
test('check that all ships have been sunk, with multiple ships', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([2, 4], 3, 'horizontal')
  gameboardObject.placeShip([7, 2], 2, 'vertical')
  gameboardObject.receiveAttack([2, 4])
  gameboardObject.receiveAttack([3, 4])
  gameboardObject.receiveAttack([4, 4])
  gameboardObject.receiveAttack([7, 2])
  gameboardObject.receiveAttack([7, 3])
  expect(gameboardObject.areShipsSunk()).toBe(true)
})
test('check that all ships have not been sunk, with multiple ships', () => {
  const gameboardObject = gameboardFactory()
  gameboardObject.placeShip([2, 4], 3, 'horizontal')
  gameboardObject.placeShip([7, 2], 2, 'vertical')
  gameboardObject.receiveAttack([2, 4])
  gameboardObject.receiveAttack([3, 4])
  gameboardObject.receiveAttack([4, 4])
  gameboardObject.receiveAttack([7, 2])
  expect(gameboardObject.areShipsSunk()).toBe(false)
})
